#!/bin/bash

declare -a Alphabet
Alphabet=(a b c d e f g h i j k l m n o p q r s t u v w x y z)
num_words=${#Alphabet[*]}

lines=$((RANDOM%100))
buf=100
zero=0
while [ "$lines" -gt "$zero" ]
do
    length=$((RANDOM%$buf + RANDOM%($buf/2)))
    s1=
    s2=
    while [ "$length" -gt "$zero" ]
    do
        c="${Alphabet[$((RANDOM%num_words))]}"
        s1=${s1}"$c"
        s2=${s2}"$c"*
        let "length -= 1"
    done 
    echo ""
    let "lines -= 1"
    res=`echo -n "$s2" | ./main "echo"`
    if [ "$s1" == "$res" ]
    then
        echo "done"
    else
        echo "fail"
        echo "$res"
        echo -ne "\n"
        echo "$s1"
        echo -ne "\n"
        echo "$s2"
    fi
done
exit 0
